services:
  db:
    container_name: postgres
    image: postgres:13.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bulletin_board_db
    volumes:
    - db:/data/postgres
    ports:
    - "5432:5432"
    networks:
    - db
    restart: unless-stopped

networks:
  db:
    driver: bridge
volumes:
  db: